### ISSUE TITLE
Unable to open EPSG support file gcs.csv

### ISSUE THREAD

**Issue by zxdawn** [conda-forge/rasterio-feedstock#123] opened 2019-05-01 02:47 UTC
Issue:
When I `import rasterio`, I got this warning:
```
proj_create: Cannot find proj.db
proj_create: no database context specified
ERROR 4: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.
```

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at E:\miniconda\envs\satpy:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
appdirs                   1.4.3                      py_1    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
blas                      1.0                         mkl    defaults
bokeh                     1.1.0                    py36_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36hb32ad35_0    conda-forge
cftime                    1.0.3.4         py36h452e1ab_1000    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
cloudpickle               0.8.1                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              2.6.1            py36hb32ad35_0    conda-forge
curl                      7.64.1               h4496350_0    conda-forge
cytoolz                   0.9.0.1         py36hfa6e2cd_1001    conda-forge
dask                      1.2.0                      py_0    conda-forge
dask-core                 1.2.0                      py_0    conda-forge
distributed               1.27.1                   py36_0    conda-forge
docutils                  0.14                  py36_1001    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
gdal                      2.4.1            py36hdf5ee75_2    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.5.1                h7bfc4c5_1    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
h5py                      2.9.0           nompi_py36h3cb27cb_1102    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
heapdict                  1.0.0                 py36_1000    conda-forge
icc_rt                    2019.0.0             h0cc432a_1    defaults
idna                      2.8                   py36_1000    conda-forge
intel-openmp              2019.3                      203    defaults
jinja2                    2.10.1                     py_0    conda-forge
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                     7_mkl    conda-forge
libcblas                  3.8.0                     7_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.1                h47faea2_2    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                     7_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.2                 hb0bdaea_1    conda-forge
libspatialite             4.3.0a            h505de5d_1027    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h36446d0_1001    conda-forge
libxml2                   2.9.9                h9ce36c8_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
m2w64-expat               2.1.1                         2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-xz                  5.2.2                         2    defaults
markupsafe                1.1.1            py36hfa6e2cd_0    conda-forge
mkl                       2019.3                      203    defaults
msgpack-python            0.6.1            py36he980bc4_0    conda-forge
msys2-conda-epoch         20160418                      1    defaults
netcdf4                   1.5.0.1          py36h2b7c3b1_0    conda-forge
numpy                     1.16.3           py36h873a0b8_0    conda-forge
olefile                   0.46                       py_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py36h6538335_0    conda-forge
partd                     0.3.9                      py_0    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
pillow                    6.0.0            py36h9a613e6_0    conda-forge
pip                       19.1                     py36_0    defaults
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h06f7779_1    conda-forge
proj4                     6.0.0                ha7a8c7b_0    conda-forge
psutil                    5.6.2            py36hfa6e2cd_0    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pykdtree                  1.3.1           py36h452e1ab_1002    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyorbital                 1.5.0                      py_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    2.1.3                    pypi_0    pypi
pyreadline                2.1                   py36_1000    conda-forge
pyresample                1.12.1           py36h830ac7b_0    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
pyspectral                0.8.8                      py_0    conda-forge
python                    3.6.8                h9f7ef89_7    defaults
python-dateutil           2.8.0                      py_0    conda-forge
python-geotiepoints       1.1.8            py36h452e1ab_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    5.1              py36hfa6e2cd_0    conda-forge
rasterio                  1.0.22           py36hbf02ebe_1    conda-forge
requests                  2.21.0                py36_1000    conda-forge
satpy                     0.14.2             pyh326bf55_0    conda-forge
scipy                     1.2.1            py36h29ff71c_0    defaults
setuptools                41.0.1                   py36_0    defaults
six                       1.12.0                py36_1000    conda-forge
snuggs                    1.4.3                      py_0    conda-forge
sortedcontainers          2.1.0                      py_0    conda-forge
sqlite                    3.28.0               he774522_0    defaults
tblib                     1.3.2                      py_1    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
toolz                     0.9.0                      py_1    conda-forge
tornado                   6.0.2            py36hfa6e2cd_0    conda-forge
tqdm                      4.31.1                     py_0    conda-forge
trollimage                1.7.0                      py_0    conda-forge
trollsift                 0.3.2                      py_0    conda-forge
urllib3                   1.24.2                   py36_0    conda-forge
vc                        14.1                 h0510ff6_4    defaults
vs2015_runtime            14.15.26706          h3a45250_4    defaults
wheel                     0.33.1                   py36_0    defaults
win_inet_pton             1.1.0                    py36_0    conda-forge
wincertstore              0.2              py36h7fe50ca_0    defaults
xarray                    0.12.1                     py_0    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
yaml                      0.1.7             hfa6e2cd_1001    conda-forge
zict                      0.1.4                      py_0    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : satpy
    active env location : E:\miniconda\envs\satpy
            shell level : 1
       user config file : C:\Users\Xin\.condarc
 populated config files : C:\Users\Xin\.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : E:\miniconda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
                          https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : E:\miniconda\pkgs
                          C:\Users\Xin\.conda\pkgs
                          C:\Users\Xin\AppData\Local\conda\conda\pkgs
       envs directories : E:\miniconda\envs
                          C:\Users\Xin\.conda\envs
                          C:\Users\Xin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment] 2019-05-01 03:15
I wonder if it is related to the PROJ_DIR environment variable. Would you mind posting that along with the GDAL_DATA environment variable?

**Comment by snowman2** [comment] 2019-05-01 03:16
One temporary solution would be to pin proj4<6.0.0.

**Comment by zxdawn** [comment] 2019-05-01 03:18
@snowman2 
PROJ_DIR is empty;
GDAL_DATA is `E:\miniconda\envs\satpy/Library/share/gdal`.

**Comment by snowman2** [comment] 2019-05-01 03:24
@ocefpaf, I think that gdal may need to look into how it manages the data directory for PROJ 6.0.0. 

@zxdawn, what happens to your environment variables if you deactivate and reactivate your conda environment?

**Comment by zxdawn** [comment] 2019-05-01 03:30
> One temporary solution would be to pin proj4<6.0.0.

After specifying proj4=5.2.0, it's solved temporarily.

> @ocefpaf, I think that gdal may need to look into how it manages the data directory for PROJ 6.0.0.
> 
> @zxdawn, what happens to your environment variables if you deactivate and reactivate your conda environment?

@snowman2 it's as same as before.

**Comment by snowman2** [comment] 2019-05-01 03:37
Apologies, I meant `PROJ_LIB` not PROJ_DIR.

**Comment by zxdawn** [comment] 2019-05-01 03:38
> PROJ_LIB

`PROJ_LIB` is empty too.

**Comment by ocefpaf** [comment] 2019-05-01 13:45
> @ocefpaf, I think that gdal may need to look into how it manages the data directory for PROJ 6.0.0.

You mean the `gdal` package or the software upstream? The former I can try to do something :-)

BTW I notice that you are getting `pyproj` from PyPI and thay probably brings its own `proj.4` static linked to it. So maybe that is the culprit here.

```
proj4                     6.0.0                ha7a8c7b_0    conda-forge
pyproj                    2.1.3                    pypi_0    pypi
```

**Comment by ocefpaf** [comment] 2019-05-01 13:58
I just tested it on Windows and everything works as expected. You are probably having issues b/c of the mixed conda/pip stuff.

```
conda create --name TEST python=3.6 rasterio pyproj --yes
conda activate TEST
python -c "import rasterio; print(rasterio.__version__)"
1.0.22
```

```
conda info

     active environment : TEST
    active env location : C:\Users\filipe\Miniconda3\envs\TEST
            shell level : 2
       user config file : C:\Users\filipe\.condarc
 populated config files : C:\Users\filipe\.condarc
          conda version : 4.6.14
    conda-build version : 3.17.8
         python version : 3.7.3.final.0
       base environment : C:\Users\filipe\Miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\Users\filipe\Miniconda3\pkgs
                          C:\Users\filipe\.conda\pkgs
                          C:\Users\filipe\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\filipe\Miniconda3\envs
                          C:\Users\filipe\.conda\envs
                          C:\Users\filipe\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.3 Windows/10 Windows/10.0.17763
          administrator : False
             netrc file : None
           offline mode : False
```

```
conda list
# packages in environment at C:\Users\filipe\Miniconda3\envs\TEST:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.1               h4496350_0    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.5.1                h7bfc4c5_1    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
intel-openmp              2019.3                      203    defaults
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.1                h47faea2_2    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.2                 hb0bdaea_1    conda-forge
libspatialite             4.3.0a            h505de5d_1027    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h016b793_1002    conda-forge
libxml2                   2.9.9                h9ce36c8_0    conda-forge
m2w64-expat               2.1.1                         2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-xz                  5.2.2                         2    defaults
mkl                       2019.3                      203    defaults
msys2-conda-epoch         20160418                      1    defaults
numpy                     1.16.3           py36h873a0b8_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h06f7779_1    conda-forge
proj4                     6.0.0                ha7a8c7b_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    2.1.3            py36h2ea4b28_1    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
rasterio                  1.0.22           py36hbf02ebe_1    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
snuggs                    1.4.3                      py_0    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
zstd                      1.3.3                    vc14_1    conda-forge
```

```
echo %PROJ_LIB%
C:\Users\filipe\Miniconda3\envs\TEST\Library\share\proj

echo %GDAL_DATA%
C:\Users\filipe\Miniconda3\envs\TEST\Library\share\gdal
````

PS: I'm using latest `conda` and `strict` channel option. Here is my `.condarc`:

```
show_channel_urls: true
add_pip_as_python_dependency: false
channel_priority: strict
channels:
  - conda-forge
  - defaults
safety_checks: disabled
auto_update_conda: false
```

**Comment by djhoese** [comment] 2019-05-01 14:02
@ocefpaf I was helping @zxdawn with this and they originally started with it installed from conda. I asked them to install from PyPI to see if that package included the data files.

**Comment by ocefpaf** [comment] 2019-05-01 14:04
Can you try my steps from https://github.com/conda-forge/rasterio-feedstock/issues/123#issuecomment-488289195 and see if that solves the issue? The important parts are: install latest conda, set `strict` channel and add conda-forge on top of `defaults`. If that does not work we can reopen this but I could not reproduce it on my Windows machine.

**Comment by snowman2** [comment] 2019-05-01 14:17
Thanks @ocefpaf!

**Comment by zxdawn** [comment] 2019-05-01 14:44
@ocefpaf Thanks! However, I tried same steps from https://github.com/conda-forge/rasterio-feedstock/issues/123#issuecomment-488289195 and still got the same error.

Content of `~/.condarc`:
```
show_channel_urls: true
add_pip_as_python_dependency: false
channel_priority: strict
channels:
  - conda-forge
  - defaults
safety_checks: disabled
auto_update_conda: false
```

```
$ echo $PROJ_LIB

$ echo $GDAL_DATA
E:\miniconda\envs\TEST/Library/share/gdal
```

`conda info`:
<details>

```
$ conda info
     active environment : TEST
    active env location : E:\miniconda\envs\TEST
            shell level : 2
       user config file : C:\Users\Xin\.condarc
 populated config files : C:\Users\Xin\.condarc
          conda version : 4.6.14
    conda-build version : not installed
         python version : 3.7.1.final.0
       base environment : E:\miniconda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/win-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : E:\miniconda\pkgs
                          C:\Users\Xin\.conda\pkgs
                          C:\Users\Xin\AppData\Local\conda\conda\pkgs
       envs directories : E:\miniconda\envs
                          C:\Users\Xin\.conda\envs
                          C:\Users\Xin\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.6.14 requests/2.21.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

`conda list`:
<details>
```
# packages in environment at E:\miniconda\envs\TEST:
#
# Name                    Version                   Build  Channel
affine                    2.2.2                      py_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
boost-cpp                 1.68.0            h6a4c333_1000    conda-forge
bzip2                     1.0.6             hfa6e2cd_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.1.1                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
curl                      7.64.1               h4496350_0    conda-forge
expat                     2.2.5             he025d50_1002    conda-forge
freetype                  2.10.0               h5db478b_0    conda-forge
freexl                    1.0.5             hd288d7e_1002    conda-forge
geos                      3.7.1             he025d50_1000    conda-forge
geotiff                   1.5.1                h7bfc4c5_1    conda-forge
gettext                   0.19.8.1          hb01d8f6_1002    conda-forge
glib                      2.58.3            hc0c2ac7_1001    conda-forge
hdf4                      4.2.13            hf8e6fe8_1002    conda-forge
hdf5                      1.10.4          nompi_hcc15c50_1106    conda-forge
intel-openmp              2019.3                      203    defaults
jpeg                      9c                hfa6e2cd_1001    conda-forge
kealib                    1.4.10            heacb130_1003    conda-forge
krb5                      1.16.3            hdd46e55_1001    conda-forge
libblas                   3.8.0                     8_mkl    conda-forge
libcblas                  3.8.0                     8_mkl    conda-forge
libcurl                   7.64.1               h4496350_0    conda-forge
libffi                    3.2.1             h6538335_1006    conda-forge
libgdal                   2.4.1                h47faea2_2    conda-forge
libiconv                  1.15              hfa6e2cd_1005    conda-forge
libkml                    1.3.0             h4fd0f3b_1009    conda-forge
liblapack                 3.8.0                     8_mkl    conda-forge
libnetcdf                 4.6.2             h396784b_1001    conda-forge
libpng                    1.6.37               h7602738_0    conda-forge
libpq                     11.2                 hb0bdaea_1    conda-forge
libspatialite             4.3.0a            h505de5d_1027    conda-forge
libssh2                   1.8.2                h642c060_2    conda-forge
libtiff                   4.0.10            h016b793_1002    conda-forge
libxml2                   2.9.9                h9ce36c8_0    conda-forge
m2w64-expat               2.1.1                         2    defaults
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gettext             0.19.7                        2    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libiconv            1.14                          6    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
m2w64-xz                  5.2.2                         2    defaults
mkl                       2019.3                      203    defaults
msys2-conda-epoch         20160418                      1    defaults
numpy                     1.16.3           py36h873a0b8_0    conda-forge
openjpeg                  2.3.1                ha922770_0    conda-forge
openssl                   1.1.1b               hfa6e2cd_2    conda-forge
pcre                      8.41              h6538335_1003    conda-forge
poppler                   0.67.0               heddaa77_6    conda-forge
poppler-data              0.4.9                         1    conda-forge
postgresql                11.2                 h06f7779_1    conda-forge
proj4                     6.0.0                ha7a8c7b_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyproj                    2.1.3            py36h2ea4b28_1    conda-forge
python                    3.6.7             he025d50_1004    conda-forge
rasterio                  1.0.22           py36hbf02ebe_1    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
snuggs                    1.4.3                      py_0    conda-forge
sqlite                    3.26.0            hfa6e2cd_1001    conda-forge
tk                        8.6.9             hfa6e2cd_1001    conda-forge
vc                        14                            0    conda-forge
vs2015_runtime            14.0.25420                    0    conda-forge
wincertstore              0.2                   py36_1002    conda-forge
xerces-c                  3.2.2             h6538335_1001    conda-forge
xz                        5.2.4             h2fa13f4_1001    conda-forge
zlib                      1.2.11            h2fa13f4_1004    conda-forge
zstd                      1.3.3                    vc14_1    conda-forge
```
</details>

**Comment by ocefpaf** [comment] 2019-05-01 14:53
The fact that you did `echo $PROJ_LIB` instead of `echo %PROJ_LIB%` makes assume you are using some sort of shell on Windows. If so we don't have the same logic for the environment variables in our package yet for that. (We do have them for `gdal` and it should be easy to port.)

If that is the case, for now I recommend you to use Windows command prompt until we can fix that.

**Comment by zxdawn** [comment] 2019-05-01 14:59
@ocefpaf Thank you! The Windows command prompt works fine.

**Comment by ocefpaf** [comment] 2019-05-16 15:35
This should be fixed in https://github.com/conda-forge/proj.4-feedstock/pull/41

**Closed by ocefpaf** 2019-05-16 15:35 UTC
