### ISSUE TITLE
CPLE_OpenFailedError encountered trying to open GeoTiff

### ISSUE THREAD

**Issue by d-diaz** [conda-forge/rasterio-feedstock#89] opened 2018-11-11 22:37 UTC
Issue: CPLE_OpenFailedError encountered trying to open GeoTiff

You should be able to recreate this computing environment if you follow the Binder link from my [GitHub repo.](https://github.com/d-diaz/Lidar_Plot_Registration])

Here's the environment.yml file contents used to build the computing environment:

```
name: viz3d
channels:
  - conda-forge
  - defaults
dependencies:
  - geopandas
  - ipywidgets
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pdal
  - plotly
  - python=3
  - python-pdal
  - rasterio
  - seaborn
prefix: /Users/daviddiaz/anaconda3/envs/viz3d
```

Here's how I encountered the error:
```
import rasterio  
src = rasterio.open('../data/external/lee_forest/lee_terrain_clipped.tif')
---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
rasterio/_base.pyx in rasterio._base.DatasetBase.__init__()

rasterio/_shim.pyx in rasterio._shim.open_dataset()

rasterio/_err.pyx in rasterio._err.exc_wrap_pointer()

CPLE_OpenFailedError: '../data/external/lee_forest/lee_terrain_clipped.tif' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

RasterioIOError                           Traceback (most recent call last)
<ipython-input-3-895f0ffa281e> in <module>()
----> 1 src = rasterio.open('../data/external/lee_forest/lee_terrain_clipped.tif')

/srv/conda/lib/python3.6/site-packages/rasterio/env.py in wrapper(*args, **kwds)
    396 
    397         with env_ctor(session=session):
--> 398             return f(*args, **kwds)
    399 
    400     return wrapper

/srv/conda/lib/python3.6/site-packages/rasterio/__init__.py in open(fp, mode, driver, width, height, count, crs, transform, dtype, nodata, sharing, **kwargs)
    215         # None.
    216         if mode == 'r':
--> 217             s = DatasetReader(path, driver=driver, **kwargs)
    218         elif mode == 'r+':
    219             s = get_writer_for_path(path)(path, mode, driver=driver, **kwargs)

rasterio/_base.pyx in rasterio._base.DatasetBase.__init__()

RasterioIOError: '../data/external/lee_forest/lee_terrain_clipped.tif' not recognized as a supported file format.
```
<br>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /srv/conda:
#
# Name                    Version                   Build  Channel
affine                    2.2.1                      py_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
attrs                     18.2.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
blas                      1.1                    openblas    conda-forge
bleach                    2.1.4                      py_1    conda-forge
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto3                     1.9.41                     py_0    conda-forge
botocore                  1.12.42                    py_0    conda-forge
bzip2                     1.0.6                h470a237_2    conda-forge
ca-certificates           2018.10.15           ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
certifi                   2018.10.15            py36_1000    conda-forge
cffi                      1.11.5           py36h5e8e0c9_1    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
click-plugins             1.0.4                      py_0    conda-forge
cligj                     0.5.0                      py_0    conda-forge
conda                     4.5.11                py36_1000    conda-forge
conda-env                 2.6.0                         1    defaults
cryptography              2.3.1            py36hdffb7b8_0    conda-forge
cryptography-vectors      2.3.1                 py36_1000    conda-forge
curl                      7.62.0               h74213dd_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
defusedxml                0.5.0                    py36_0    conda-forge
descartes                 1.1.0                      py_2    conda-forge
docutils                  0.14                  py36_1001    conda-forge
entrypoints               0.2.3                    py36_2    conda-forge
expat                     2.2.5                hfc679d8_2    conda-forge
fiona                     1.7.13           py36hb00a9d7_4    conda-forge
flann                     1.9.1                hd60c8bd_3    conda-forge
fontconfig                2.13.1               h65d0f4c_0    conda-forge
freetype                  2.9.1                h6debe1e_4    conda-forge
freexl                    1.0.5                h470a237_2    conda-forge
gdal                      2.2.4           py36hb00a9d7_10    conda-forge
geopandas                 0.4.0                      py_1    conda-forge
geos                      3.6.2                hfc679d8_3    conda-forge
geotiff                   1.4.2                h700e5ad_5    conda-forge
gettext                   0.19.8.1             h5e8e0c9_1    conda-forge
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
gmp                       6.1.2                hfc679d8_0    conda-forge
gst-plugins-base          1.12.5               hde13a9d_0    conda-forge
gstreamer                 1.12.5               h61a6719_0    conda-forge
hdf4                      4.2.13               h951d187_2    conda-forge
hdf5                      1.10.3               hc401514_2    conda-forge
hexer                     1.4.0                         1    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                   py36_1002    conda-forge
ipykernel                 4.9.0                    py36_0    conda-forge
ipython                   6.5.0                    py36_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jedi                      0.12.1                   py36_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
jsoncpp                   1.8.1                h2d50403_1    conda-forge
jsonschema                2.6.0                    py36_2    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py36_1    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.34.9                   py36_0    conda-forge
jupyterlab_launcher       0.13.1                     py_2    conda-forge
kealib                    1.4.10               hb88cf67_0    conda-forge
kiwisolver                1.0.1            py36h2d50403_2    conda-forge
krb5                      1.16.2               hbb41f41_0    conda-forge
laszip                    3.2.2                hfc679d8_2    conda-forge
laz-perf                  1.2.0                hfc679d8_2    conda-forge
libcurl                   7.62.0               hbdb9355_0    conda-forge
libdap4                   3.19.1               h8fe5423_1    conda-forge
libedit                   3.1.20170329         h6b74fdf_2    defaults
libffi                    3.2.1                hfc679d8_5    conda-forge
libgcc-ng                 7.2.0                hdf63c60_3    conda-forge
libgdal                   2.2.4               h744ea89_10    conda-forge
libgfortran               3.0.0                         1    conda-forge
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1               h9cd6fdc_11    conda-forge
libpng                    1.6.35               ha92aebf_2    conda-forge
libpq                     10.3                 h1ad7b7a_0    defaults
libsodium                 1.0.16               h470a237_1    conda-forge
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a              hdfcc80b_23    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libstdcxx-ng              7.2.0                hdf63c60_3    conda-forge
libtiff                   4.0.9                he6b73bb_2    conda-forge
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.13                 h470a237_2    conda-forge
libxml2                   2.9.8                h422b904_5    conda-forge
markupsafe                1.0              py36h470a237_1    conda-forge
matplotlib                3.0.1                h8a2030e_1    conda-forge
matplotlib-base           3.0.1            py36hc039c98_1    conda-forge
mistune                   0.8.3            py36h470a237_2    conda-forge
munch                     2.3.2                      py_0    conda-forge
nbconvert                 5.4.0                         1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
nitro                     2.7.dev3             hfc679d8_0    conda-forge
notebook                  5.6.0                    py36_1    conda-forge
nteract-on-jupyter        1.9.6                     <pip>
numpy                     1.15.4          py36_blas_openblashb06ca3d_0  [blas_openblas]  conda-forge
openblas                  0.3.3                ha44fe06_1    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openssl                   1.0.2p               h470a237_1    conda-forge
packaging                 18.0                       py_0    conda-forge
pandas                    0.23.4           py36hf8a1672_0    conda-forge
pandoc                    1.19.2                        0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.3.1                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcl                       1.8.1                h3a4cd21_2    conda-forge
pcre                      8.41                 hfc679d8_3    conda-forge
pdal                      1.7.2            py36hfeb630d_3    conda-forge
pexpect                   4.6.0                    py36_0    conda-forge
pickleshare               0.7.4                    py36_0    conda-forge
pip                       18.0                     py36_1    conda-forge
pixman                    0.34.0               h470a237_3    conda-forge
plotly                    3.4.1                      py_0    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                10.3                 h1ad7b7a_0    defaults
proj4                     4.9.3                h470a237_8    conda-forge
prometheus_client         0.3.1                      py_1    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psycopg2                  2.7.5            py36hdffb7b8_2    conda-forge
pthread-stubs             0.4                  h470a237_1    conda-forge
ptyprocess                0.6.0                    py36_0    conda-forge
pycosat                   0.6.3            py36h470a237_1    conda-forge
pycparser                 2.19                       py_0    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyopenssl                 18.0.0                py36_1000    conda-forge
pyparsing                 2.3.0                      py_0    conda-forge
pyproj                    1.9.5.1          py36h508ed2a_6    conda-forge
pyqt                      5.6.0            py36h8210e8a_7    conda-forge
pysal                     1.14.4.post2          py36_1001    conda-forge
pysocks                   1.6.8                 py36_1002    conda-forge
python                    3.6.6                h5001a0f_3    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
python-pdal               2.0.0            py36h3e44d54_1    conda-forge
pytz                      2018.7                     py_0    conda-forge
pyzmq                     17.1.2           py36hae99301_0    conda-forge
qt                        5.6.2                hf70d934_9    conda-forge
qtconsole                 4.4.3                      py_0    conda-forge
rasterio                  1.0.9            py36h1b5fcde_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.20.0                py36_1000    conda-forge
retrying                  1.3.3                      py_2    conda-forge
rtree                     0.8.3                 py36_1000    conda-forge
ruamel_yaml               0.15.71          py36h470a237_0    conda-forge
s3transfer                0.1.13                py36_1001    conda-forge
scipy                     1.1.0           py36_blas_openblashb06ca3d_202  [blas_openblas]  conda-forge
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                40.2.0                   py36_0    conda-forge
shapely                   1.6.4            py36h164cb2d_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.18.1           py36hfc679d8_0    conda-forge
six                       1.11.0                   py36_1    conda-forge
snuggs                    1.4.1                      py_1    conda-forge
sqlalchemy                1.2.13           py36h470a237_0    conda-forge
sqlite                    3.25.3               hb1c47c0_0    conda-forge
statsmodels               0.9.0            py36h7eb728f_0    conda-forge
terminado                 0.8.1                    py36_1    conda-forge
testpath                  0.3.1                    py36_1    conda-forge
tk                        8.6.8                         0    conda-forge
tornado                   4.5.3                    py36_0    conda-forge
traitlets                 4.3.2                    py36_0    conda-forge
urllib3                   1.23                  py36_1001    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.31.1                   py36_1    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
xerces-c                  3.2.0                h5d6a6da_2    conda-forge
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxau               1.0.8                h470a237_6    conda-forge
xorg-libxdmcp             1.1.2                h470a237_7    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.5                hfc679d8_5    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : None
       user config file : /home/jovyan/.condarc
 populated config files : /srv/conda/.condarc
          conda version : 4.5.11
    conda-build version : not installed
         python version : 3.6.6.final.0
       base environment : /srv/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/linux-64
                          https://repo.anaconda.com/pkgs/pro/noarch
          package cache : /srv/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /srv/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.5.11 requests/2.20.0 CPython/3.6.6 Linux/4.14.56+ ubuntu/18.04 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by ocefpaf** [comment] 2018-11-12 16:38
I don't have your GeoTiff to test but I did test with the one in [rasterio test/data folder](https://github.com/mapbox/rasterio/blob/master/tests/data/RGB.byte.tif) and everything worked as expected. The main difference is that I do not use `defaults` at all in my envs and the packages you are getting from `defaults` there may be the culprit.

**Comment by d-diaz** [comment] 2018-11-13 03:06
Don't think the packages from the defaults are the culprit. Those are `conda-env`, `libedit`, `libpq`, `postgresql`, and `yaml`. I wouldn't think any of these packages would be involved with a call to open a GeoTiff. I tried creating another environment without the defaults channel listed, and the same error persists.

The [rasterio documentation](https://rasterio.readthedocs.io/en/latest/api/rasterio._err.html) indicates `CPLE_OpenFailedError` is related to the GDAL API. I would imagine this has something to do with some incompatibility between the versions of GDAL and rasterio that got installed. 

I get the same error when I try using the file you suggested:

```
src = rasterio.open('https://github.com/mapbox/rasterio/blob/master/tests/data/RGB.byte.tif')

---------------------------------------------------------------------------
CPLE_OpenFailedError                      Traceback (most recent call last)
rasterio/_base.pyx in rasterio._base.DatasetBase.__init__()

rasterio/_shim.pyx in rasterio._shim.open_dataset()

rasterio/_err.pyx in rasterio._err.exc_wrap_pointer()

CPLE_OpenFailedError: '/vsicurl/https://github.com/mapbox/rasterio/blob/master/tests/data/RGB.byte.tif' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

RasterioIOError                           Traceback (most recent call last)
<ipython-input-3-ef14bbe417d1> in <module>()
----> 1 src = rasterio.open('https://github.com/mapbox/rasterio/blob/master/tests/data/RGB.byte.tif')

/srv/conda/lib/python3.6/site-packages/rasterio/env.py in wrapper(*args, **kwds)
    396 
    397         with env_ctor(session=session):
--> 398             return f(*args, **kwds)
    399 
    400     return wrapper

/srv/conda/lib/python3.6/site-packages/rasterio/__init__.py in open(fp, mode, driver, width, height, count, crs, transform, dtype, nodata, sharing, **kwargs)
    215         # None.
    216         if mode == 'r':
--> 217             s = DatasetReader(path, driver=driver, **kwargs)
    218         elif mode == 'r+':
    219             s = get_writer_for_path(path)(path, mode, driver=driver, **kwargs)

rasterio/_base.pyx in rasterio._base.DatasetBase.__init__()

RasterioIOError: '/vsicurl/https://github.com/mapbox/rasterio/blob/master/tests/data/RGB.byte.tif' not recognized as a supported file format.
```

**Comment by sgillies** [comment] 2018-11-13 05:52
@d-diaz GDAL has so many ways to fail to read a dataset and Rasterio doesn't always surface the best exception messages. The "/vsicurl/https" in yours, though, suggests to me that this error comes down to libcurl and SSL certs. I'd check the latter.

**Comment by ocefpaf** [comment] 2018-11-13 12:20
@d-diaz that is a different error from the original comment, no?
I can confirm that `/vsicurl/https` is not working. I'll look into it. Thanks for reporting.

**Comment by ocefpaf** [comment] 2018-11-13 12:22
Actually the URL in your example is not OK. It does not point to the data. It should be:

https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif

That one works just fine for me. Closing this b/c I cannot reproduce your original error and the second one is solved :smile:

**Closed by ocefpaf** 2018-11-13 12:22 UTC

**Comment by d-diaz** [comment] 2018-11-13 19:44
@ocefpaf, you can reproduce both of the errors by firing up the binder service I mentioned at my github repo. I suspect these are the exact same error, that whatever versions of rasterio and GDAL installed cannot read the tiff. The error is not that it can't find the file. 

Here is the link to get the environment set up for you: [https://mybinder.org/v2/gh/d-diaz/Lidar_Plot_Registration/master](https://mybinder.org/v2/gh/d-diaz/Lidar_Plot_Registration/master)

Once that environment loads an instance in the cloud with the packages installed (may take ~10 minutes, so be patient), you can open a new terminal from the Jupyter interface, start ipython, and then reproduce everything I've posted. As you can see in the code snippet I posted above when you asked me to point at the RGB.byte.tif, I did type it in correctly. the `/vsicurl` prefix was not added by my, but believe that is added by GDAL. 

If you want direct access to the tiff I used via http, you can find it here: [https://github.com/d-diaz/Lidar_Plot_Registration/blob/master/data/external/lee_forest/lee_terrain_clipped.tif](https://github.com/d-diaz/Lidar_Plot_Registration/blob/master/data/external/lee_forest/lee_terrain_clipped.tif)

Here's how you would reproduce the error from a terminal opened in binder:
```
ipython
...
[1] import rasterio
[2] src = rasterio.open('../data/external/lee_forest/lee_terrain_clipped.tif')
... CPLE_OpenFailedError ...

[3] src2 = rasterio.open('https://github.com/mapbox/rasterio/raw/master/tests/data/RGB.byte.tif')
... CPLE_OpenFailedError ...
```

**Comment by d-diaz** [comment] 2018-11-13 20:12
Update... I think it's related to using a relative path.

When I try to open my tiff via URL, it works:
```
src = rasterio.open(src = rasterio.open('https://github.com/ddiaz/Lidar_Plot_Registration/blob/master/data/external/lee_forest/lee_terrain_clipped.tif?raw=true')
```
Notice that I added `?raw=true` to the end of the URL for the tiff. 

However, when I use a relative path to the tiff it fails, even though it's apparent that the file exists:
```
In[5]: os.path.exists('./data/external/lee_forest/lee_terrain_clipped.tif')
Out[5]: True
In[6]: src = rasterio.open('./data/external/lee_forest/lee_terrain_clipped.tif')
Out[6]: ... CPLE_OpenFailedError ...
```

**Comment by snowman2** [comment] 2018-11-16 03:04
@d-diaz it appears that your git repository itself has issues (something appears corrupted). I created the environment with your environment.yml and here are the results.

Raw file download:
```
$ wget https://github.com/d-diaz/Lidar_Plot_Registration/blob/master/data/external/lee_forest/lee_terrain_clipped.tif?raw=true -O lee_terrain_clipped.tif
(viz3d) $ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
>>> rds = rasterio.open('lee_terrain_clipped.tif')
>>> rds.profile
{'driver': 'GTiff', 'dtype': 'float32', 'nodata': 0.0, 'width': 319, 'height': 278, 'count': 1, 'crs': CRS({'init': 'epsg:2926'}), 'transform': Affine(3.0, 0.0, 1323765.0,
       0.0, -3.0, 302826.0), 'tiled': False, 'interleave': 'band'}
```
Direct URL access:
```
(viz3d) $ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
>>> rds = rasterio.open('https://github.com/d-diaz/Lidar_Plot_Registration/blob/master/data/external/lee_forest/lee_terrain_clipped.tif?raw=true')
>>> rds.profile
{'driver': 'GTiff', 'dtype': 'float32', 'nodata': 0.0, 'width': 319, 'height': 278, 'count': 1, 'crs': CRS({'init': 'epsg:2926'}), 'transform': Affine(3.0, 0.0, 1323765.0,
       0.0, -3.0, 302826.0), 'tiled': False, 'interleave': 'band'}
```
However, when I cloned the repo:
```
~/scratch$ git clone git@github.com:d-diaz/Lidar_Plot_Registration.git
~/scratch$ cd Lidar_Plot_Registration/data/external/lee_forest
(viz3d) ~/scratch/Lidar_Plot_Registration/data/external/lee_forest$ python
Python 3.6.6 | packaged by conda-forge | (default, Oct 12 2018, 14:08:43) 
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import rasterio
>>> rds = rasterio.open('lee_terrain_clipped.tif')
Traceback (most recent call last):
  File "rasterio/_base.pyx", line 199, in rasterio._base.DatasetBase.__init__
  File "rasterio/_shim.pyx", line 64, in rasterio._shim.open_dataset
  File "rasterio/_err.pyx", line 194, in rasterio._err.exc_wrap_pointer
rasterio._err.CPLE_OpenFailedError: 'lee_terrain_clipped.tif' not recognized as a supported file format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/miniconda/envs/viz3d/lib/python3.6/site-packages/rasterio/env.py", line 398, in wrapper
    return f(*args, **kwds)
  File "/home/snowal/miniconda/envs/viz3d/lib/python3.6/site-packages/rasterio/__init__.py", line 217, in open
    s = DatasetReader(path, driver=driver, **kwargs)
  File "rasterio/_base.pyx", line 201, in rasterio._base.DatasetBase.__init__
rasterio.errors.RasterioIOError: 'lee_terrain_clipped.tif' not recognized as a supported file format.
>>> exit()
```
On inspecting the file from the clone, it appears to not contain the raster data:
```
(viz3d) ~/scratch/Lidar_Plot_Registration/data/external/lee_forest$ ls -lh
total 8.0K
-rwxrwxr-x 1 user user 131 Nov 15 20:50 lee_terrain_clipped.tif
-rwxrwxr-x 1 user user 128 Nov 15 20:50 lee_terrain_clipped.tif.aux.xml
(viz3d) ~/scratch/Lidar_Plot_Registration/data/external/lee_forest$ cat lee_terrain_clipped.tif
version https://git-lfs.github.com/spec/v1
oid sha256:6d2e462acbf0b12fcee91609c79060767c63bdbff77c2022d4fb30e0a1591c41
size 355541
```

**Comment by d-diaz** [comment] 2018-11-16 22:31
Thanks for your help, @snowman2. This has resolved the issue.

The geotiffs in my repo are being managed by Git LFS. If Git LFS isn't installed on the machine you're cloning to, it seems like it only downloads the Git LFS pointers to the file instead of downloading the actual files they point to. It also seems like the Binder service doesn't have Git LFS support yet. 

When I removed tiffs from being managed by Git LFS pushed the tiffs back to the repo using Git, everything seems to be working.
