### ISSUE TITLE
libkea cannot open shared library

### ISSUE THREAD

**Issue by djhoese** [conda-forge/rasterio-feedstock#86] opened 2018-10-21 23:41 UTC
Cannot open shared library libkea.so error again on a fresh travis environment using astropy's cihelpers (nothing special, creates test environment, and activates it). Failing job: https://travis-ci.org/pytroll/pyresample/jobs/444489424#L1312

I'll try adding libkea to the dependency list to see if this fixes it. OSX jobs pass, linux jobs fail.

**Comment by djhoese** [comment] 2018-10-26 13:18
Damn, I was pretty sure I had deleted the defaults channel. Might be a problem with how our cihelpers is configured. @ocefpaf has the "strict" channel functionality been added/merged to conda yet? That should fix this issue for me right?

I remember needing to add kealib to the dependencies in the past and then I didn't need to anymore for a long time until now. Any idea what might have changed?

**Comment by ocefpaf** [comment] 2018-11-02 21:33
@djhoese closing this. Please re-open if you believe there is something we can do here, but I think the issue is with the ci-helpers.

**Closed by ocefpaf** 2018-11-02 21:33 UTC
