### ISSUE TITLE
rasterio fails on import -- 

### ISSUE THREAD

**Issue by lwasser** [conda-forge/rasterio-feedstock#144] opened 2019-09-05 17:43 UTC
Issue:

In my conda forge docker container, rasterio is not importing properly.
the error i get is:

```
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
```

<br/>
Environment (<code>conda list</code>):

to replicate this issue, please do the following

1. clone this repo: https://github.com/earthlab/earth-analytics-python-env
2. run docker build

`docker build -t earthlab/earth-analytics-python-env:latest .`
in the last step, rasterio is imported as a test. and it fails. 

I noticed the same issue with fiona / geopandas here:
https://github.com/conda-forge/fiona-feedstock/issues/137
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
please let me know if you need this. because it's a docker build i was thinking my environment should not matter but i could be wrong!  @ocefpaf is this something you are aware of? 
```
</details>

**Comment by snowman2** [comment] 2019-09-05 19:04
Did you active the environment? `conda activate`?

**Comment by lwasser** [comment] 2019-09-05 21:36
in theory this updates the base environment given it's a docker container @snowman2 . it has worked well in the past UNLESS something has changed? it's been building without issues for a few months this way! but another thing i just noticed is that it actually uses jupyter minimal notebook which has some things installed that are not from conda-forge. but it's weird it just started failing recently.

**Comment by snowman2** [comment] 2019-09-05 22:35
It's always recommended to activate your environment. It sets up your environment variables and other pieces needed for the libraries, even on a docker container. I would recommend looking at the `env` command output before and after activating the base environment.

**Comment by lwasser** [comment] 2019-09-05 23:04
ok! i'll do some more local builds to see if that helps @snowman2 !!

**Comment by lwasser** [comment] 2019-09-06 00:47
@snowman2 how do you initiatilize conda within a docker container? i ran 
```
RUN conda init bash
RUN conda activate
```

and that did not work. error

```
CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>


```

**Comment by snowman2** [comment] 2019-09-06 01:02
Huh, that's interesting. I haven't seen that before. I wonder how they have that container set up. 🤔

You could try adding a pin to proj4=5.2

**Comment by lwasser** [comment] 2019-09-06 01:24
here is a weird note:

1. the docker container actual DOES BUILD succesfully even tho that error appears
2. proj 4  is 6.1.1-- `proj4                     6.1.1                hc80f0dc_1    conda-forge`

i just tried again and i also noticed that rasterio imports just fine in the notebook (didn't try any operations just imported it. HOWEVER at the CLI in the docker container, i get that same proj4 syntax message. the environment is fully intact and accessible. it's something specific with rasterio i think?? or with proj4.

**Comment by snowman2** [comment] 2019-09-06 01:42
Ah, so it works just fine. Just an error message then? If that is the case, then the issue is that the error messages occurs when rasterio is checking that the data directory. It probably checks a few places and before the data directory is set it throws these errors.

**Comment by ocefpaf** [comment] 2019-09-06 13:38
> Ah, so it works just fine. Just an error message then? If that is the case, then the issue is that the error messages occurs when rasterio is checking that the data directory. It probably checks a few places and before the data directory is set it throws these errors.

I think so. Latest `rasterio` tries to be smarter about those paths and may be confused.

@lwasser your docker image is a thin layer and probably does not have a proper shell for `conda init`. You should use `source activate` instead of `conda init`/`conda activate`.

**Comment by lwasser** [comment] 2019-09-06 14:45
ok thank you BOTH!! so tell me -- should this build message concern me? it's popping up in red in each docker build but YES the builld does complete. 

I could try to reproject some data in the image to see if it works.

I'll try the `sourse activate` step today!! thank you both!!

**Comment by lwasser** [comment] 2019-09-06 16:55
i'm still getting that warning message @ocefpaf are there other things that i can do to unconfuse rasterio? is that something i should be concerned about? source activate and source activate root didn't seem to work but that could have been user error.

**Comment by ocefpaf** [comment] 2019-09-06 19:23
@lwasser I'm closing this b/c it is a docker image thing and not a problem with the package. I'm sending a PR to help you with that upstream.

**Closed by ocefpaf** 2019-09-06 19:23 UTC

**Comment by lwasser** [comment] 2019-09-06 23:04
thank you @ocefpaf sounds good.Just to confirm - it sounds like it has something to do with activating the environment in a container with limited setup (a thin container as you called it). do i have that correct? many thanks and happy to keep this closed.
